seed: 42
output_path: outputs/pointnet

model:
  name: pointnet2_ssg
  custom_weights_path: null
  num_classes: 2
  num_channels: 1024

dataset:
  datapath_train: data/train
  datapath_val: data/val
  num_points: 2048

dataloader:
  batch_size: 16
  num_workers: 4
  pin_memory: true

matrix:
  type: orthogonal

prototypes:
  purity_fn: argmax3d
