defaults:
  - _self_
  - pointnet_config_base

hydra:
  run:
    dir: ${output_path}/explain

exp:
  run_func: "explain"

dataloader:
  shuffle: false

visualization:
  num_explanations: 10
  num_prototypical_channels: 4
  num_prototypes: 4
